# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
      - test-edxapp
jobs:
  test-3.6:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source="." manage.py test ~/repo/eox_tenant/test
            coverage report --fail-under=51
            pycodestyle ./eox_tenant
            pylint ./eox_tenant --rcfile=./setup.cfg

  # Based on answer https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462
  test-2.7:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo27

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-27-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-27-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source="." --rcfile=.coveragerc manage.py test ~/repo27/eox_tenant/test
            coverage report --fail-under=51 --rcfile=.coveragerc
            pycodestyle ./eox_tenant
            pylint ./eox_tenant --rcfile=./setup.cfg

  test-edxapp:

    docker:
      - image: edxops/edxapp:hawthorn.master

    working_directory: /edx/src/eox-tenant

    steps:
      - checkout
      - run:
          name: Set edx-platform
          command: |
            cd /edx/app/edxapp/
            git clone -b open-release/hawthorn.master https://github.com/edx/edx-platform.git
            . /edx/app/edxapp/venvs/edxapp/bin/activate
            cd edx-platform
            pip install .
            pip install -r requirements/edx/testing.txt

      - run:
          name: Run tests
          command: |
            . /edx/app/edxapp/venvs/edxapp/bin/activate
            pip install -r requirements.txt
            python manage.py test /edx/src/eox-tenant/eox_tenant/test-edx-platform/
