# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [(b'ednx_microsites', '0001_initial'), (b'ednx_microsites', '0002_auto_20181107_2104')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=63)),
                ('subdomain', models.CharField(db_index=True, max_length=127)),
                ('values', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='microsite',
            table='ednx_microsites_microsites',
        ),
    ]
