# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-26 17:25
from __future__ import unicode_literals

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eox_tenant', '0004_remove_redirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsite',
            name='values',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='lms_configs',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='meta',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='studio_configs',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='theming_configs',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
    ]
