# Generated by Django 2.2.16 on 2020-09-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_tenant', '0005_auto_20191226_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
    ]
