# Generated by Django 2.2.16 on 2020-09-22 14:21

import collections

import jsonfield.encoder
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_tenant', '0006_tenantorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='eox_tenant.TenantOrganization'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='eox_tenant.TenantOrganization'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='lms_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='studio_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='theming_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
