# Generated by Django 3.2.18 on 2023-06-08 21:59

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0008_auto_20210910_0940'),
        ('eox_tenant', '0008_synchronize_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSiteConfigProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('site_configuration.siteconfiguration',),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='lms_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='studio_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='theming_configs',
            field=jsonfield.fields.JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
