# Generated by Django 3.2.18 on 2023-06-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dark_lang', '0003_auto_20180425_0359'),
        ('eox_tenant', '0009_auto_20230608_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkLangProxy',
            fields=[
                ('darklangconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dark_lang.darklangconfig')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
            bases=('dark_lang.darklangconfig',),
        ),
    ]
