name: Integration Tests

on:
  push:
    branches:
      - 'fmo/**'

jobs:
  edx-platform-integration-test:
    name: Integration with Palm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src/eox-tenant

      - name: Permissions
        run: |
          ls -alh src
          ls -alh src/eox-tenant
          chmod 777 src/eox-tenant

      # - name: Prepare Tutor
      #   run: |
      #     pip install "tutor<17.0.0"
      #     TUTOR_ROOT="$(pwd)" tutor config save
      #     TUTOR_ROOT="$(pwd)" tutor mounts add lms:$(pwd)/src:/openedx/src

      # - name: Launch tutor and test
      #   run: |
      #     TUTOR_ROOT="$(pwd)" tutor local launch -I
      #     TUTOR_ROOT="$(pwd)" tutor local run lms pip install -e ../src/eox-tenant
      #     TUTOR_ROOT="$(pwd)" tutor local run lms ./manage.py lms help
