name: Integration Tests

on:
  push:
    branches:
      - 'fmo/**'

jobs:
  edx-platform-integration-test:
    name: Integration with Palm
    runs-on: ubuntu-latest
    steps:
      - name: Install Tutor
        run: |
          pip install "tutor<17.0.0"
          TUTOR_ROOT="$(pwd)" tutor config save

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: eox-tenant


      - name: Tutor config
        run: |
          TUTOR_ROOT="$(pwd)" tutor config save

      - name: Introspection
        run: |
          tree -L 5

      - name: Tutor Launch
        run: |
          TUTOR_ROOT="$(pwd)" tutor mounts add eox-tenant
          TUTOR_ROOT="$(pwd)" tutor dev launch -I

      - name: Install package
        run: |
          TUTOR_ROOT="$(pwd)" tutor local run lms cd ../eox-tenant && pip install -e .
          TUTOR_ROOT="$(pwd)" tutor local run cms cd ../eox-tenant && pip install -e .

      - name: Tutor commands
        run: |
          TUTOR_ROOT="$(pwd)" tutor local run lms ./manage.py lms help
          TUTOR_ROOT="$(pwd)" tutor local run cms ./manage.py cms help
